spring:
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: http://127.0.0.1:8848
        namespace: coin-dev
  session:
    store-type: none
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: 65Yxd4PMYbTNAYHT
    url: jdbc:p6spy:mysql://194.41.36.123:3306/zhengtuo?characterEncoding=utf-8&useSSL=false
    username: zhengtuo
  jpa:
    generate-ddl: false
    show-sql: true
  data:
    mongodb:
      uri: mongodb://194.41.36.123:27017/bitrade
  ## redis服务器配置
  redis:
    database: 0
    host: 194.41.36.123
    password: Wrhwiydk6Z2
    port: 6379
    timeout: 30000
  #kafka
  kafka:
    bootstrap-servers: 194.41.36.123:9092
    producer:
      batch:
        size: 256 # 每次批处理的大小
      buffer:
        memory: 1048576 # 缓存数据的内存大小
      linger: 1 #linger指定的时间等待更多的records出现
      retries: 0 # 重传次数
    consumer:
      auto:
        commit:
          interval: 100
        offset:
          reset: earliest
      concurrency: 9
      enable:
        auto:
          commit: false
      group:
        id: default-group
      maxPollRecordsConfig: 50
      session:
        timeout: 15000
decorator:
  datasource:
    p6spy:
      log-file: spy.log
      log-format: executionTime:%(executionTime) | sql:%(sqlSingleLine)
      logging: file
